# This is a basic workflow to help you get started with Actions

name: Deploy Vuepress Docs

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install NPM project
        run: |
          set -e
          npm install
          
      - name: Build Vuepress Docs
        run : npm run docs:build
      
      - name: Change directory to dist folder
        run: |
          cd docs/.vuepress/dist
          git init
      
      - name: Commit & Push
        uses: actions-js/pusgithub_tokenh@v1.2
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: master:gh-pages
          force: true
        
          
      
