# This is a basic workflow to help you get started with Actions

name: Deploy Vuepress Docs

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy_vuepress:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install NPM project
        run: |
          set -e
          npm install
          
      - name: Build Vuepress Docs
        run : npm run docs:build
        
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      
      - name: Commit docs
        run: |
          cd docs/.vuepress/dist
          git init
          git add -A
          git commit -m "Deploy Vuepress to Github Pages"
          
          
      - name: Push
        run: |
          git push -f origin master:gh-pages
          
          
      
      
        
          
      
